MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: ""
  RPN:
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("sidewalk_train",)
  VAL: ("sidewalk_val",)
  TEST: ("sidewalk_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./out/sidewalk.frcnn.ra.bs2"